_wandb:
    value:
        cli_version: 0.22.2
        e:
            ug5omzwonxben918rgth6tluwx1dyvas:
                args:
                    - --wandb-run-id
                    - eg1fldqm
                    - --config
                    - configs/method3_3resnets_no_ce.yaml
                    - --split
                    - test
                codePath: scripts/evaluate.py
                codePathLocal: scripts/evaluate.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "113816633344"
                        used: "24199454720"
                email: bakridenov.2105666@studenti.uniroma1.it
                executable: /venv/kd-env/bin/python
                git:
                    commit: f352c94cb15e0b931df4c88c140d1cb76c2a7826
                    remote: https://github.com/Jeen-Freecs/kd_thesis.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-88917c94-eb1e-7aea-0ae3-72da76491c6d
                host: 23bcb514b0bc
                memory:
                    total: "33569599488"
                os: Linux-6.8.0-49-generic-x86_64-with-glibc2.39
                program: /workspace/kd_thesis/scripts/evaluate.py
                python: CPython 3.11.14
                root: /workspace/kd_thesis
                startedAt: "2025-10-29T01:07:01.151161Z"
                writerId: ug5omzwonxben918rgth6tluwx1dyvas
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 63
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 63
                - 103
            "3":
                - 2
                - 13
                - 15
                - 16
                - 62
            "4": 3.11.14
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
checkpoint:
    value: /workspace/kd_thesis/artifacts/model-eg1fldqm:v92/model.ckpt
config_file:
    value: configs/method3_3resnets_no_ce.yaml
device:
    value: cuda
kd_type:
    value: confidence
run_id:
    value: eg1fldqm
split:
    value: test
student_model:
    value: mobilenetv2_100
teacher_models:
    value:
        - resnet50_cifar100
        - resnet18_cifar100
        - resnet34_cifar100
temperature:
    value: 4
