_wandb:
    value:
        cli_version: 0.22.2
        e:
            ivim1zqsa0fpwj4y2mrb9hqsiuhkbuqm:
                args:
                    - --config
                    - configs/method3_densenet_resnet_temp8.yaml
                codePath: scripts/train.py
                codePathLocal: scripts/train.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "113816633344"
                        used: "30852136960"
                email: bakridenov.2105666@studenti.uniroma1.it
                executable: /venv/kd-env/bin/python
                git:
                    commit: f352c94cb15e0b931df4c88c140d1cb76c2a7826
                    remote: https://github.com/Jeen-Freecs/kd_thesis.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-88917c94-eb1e-7aea-0ae3-72da76491c6d
                host: 23bcb514b0bc
                memory:
                    total: "33569599488"
                os: Linux-6.8.0-49-generic-x86_64-with-glibc2.39
                program: /workspace/kd_thesis/scripts/train.py
                python: CPython 3.11.14
                root: .
                startedAt: "2025-10-29T03:21:03.298798Z"
                writerId: ivim1zqsa0fpwj4y2mrb9hqsiuhkbuqm
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 63
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 63
                - 103
            "3":
                - 7
                - 13
                - 66
            "4": 3.11.14
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
alpha:
    value: null
batch_size:
    value: 128
gamma:
    value: null
kd_type:
    value: confidence
learning_rate:
    value: 0.001
log_every_n_steps:
    value: 50
max_epochs:
    value: 150
num_classes:
    value: 100
num_workers:
    value: 4
patience:
    value: 30
seed:
    value: 42
student_model:
    value: mobilenetv2_100
student_pretrained:
    value: false
teacher_models:
    value:
        - densenet121_cifar100
        - resnet50_cifar100
temperature:
    value: 8
threshold:
    value: null
use_hard_loss:
    value: true
use_soft_loss:
    value: true
val_size:
    value: 5000
