_wandb:
    value:
        cli_version: 0.22.2
        e:
            4mkgs4xjldlittgt0u3kvnkgbjgsheni:
                args:
                    - --wandb-run-id
                    - 7534idpa
                    - --config
                    - configs/baseline_config.yaml
                    - --split
                    - test
                codePath: scripts/evaluate.py
                codePathLocal: scripts/evaluate.py
                email: bakridenov.2105666@studenti.uniroma1.it
                executable: /venv/kd-env/bin/python
                git:
                    commit: 2ea6042f159d53d650e001264542a2e392739422
                    remote: https://github.com/Jeen-Freecs/kd_thesis.git
                host: 23bcb514b0bc
                os: Linux-6.8.0-49-generic-x86_64-with-glibc2.39
                program: /workspace/kd_thesis/scripts/evaluate.py
                python: CPython 3.11.14
                root: /workspace/kd_thesis
                startedAt: "2025-10-28T21:03:36.504807Z"
                writerId: 4mkgs4xjldlittgt0u3kvnkgbjgsheni
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 63
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 63
                - 103
            "3":
                - 2
                - 13
                - 15
                - 16
                - 62
            "4": 3.11.14
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
checkpoint:
    value: /workspace/kd_thesis/artifacts/model-7534idpa:v17/model.ckpt
config_file:
    value: configs/baseline_config.yaml
device:
    value: cuda
run_id:
    value: 7534idpa
split:
    value: test
